#Filename: main.yml
#Author: Kyle McColgan
#Date: 4 August 2026
#Description: This file contains the GitHub Actions workflow for the GitHub Pages deployment process.

name: main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '24'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages           # The branch to push to.
        folder: dist               # Vite's build folder is dist.
        token: ${{ secrets.GH_TOKEN }}  # Using the PAT secret for deployment.
